---
title: "5 yo Ambig Analyses"
author: "Rosa Li"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
rm(list = ls())
require(ggplot2)
require(grid)
require(dplyr)
# require(xlsx)

ambig <- read.csv("./KidAmbigRaw.csv")
ambigStart <- which(colnames(ambig) == "RA6_0")
ambigEnd <- which(colnames(ambig) == "RA0_6")
ambig$PChoseRisk <- rowMeans(ambig[,ambigStart:ambigEnd])
ambigStart2 <- which(colnames(ambig) == "RA5_1")
ambigEnd2 <- which(colnames(ambig) == "RA1_5")
ambig$PChoseRisk2 <- rowMeans(ambig[,ambigStart2:ambigEnd2]) #ignores 100% win/lose risk

#remove subs who did not pass practice
fails <- ambig$P3 == 0
ambig <- ambig[!fails,]
allData <- ambig[!fails,]
```

## Plotting ambiguity attitudes
```{r, echo=FALSE, warning=FALSE, message=FALSE}
p <- ggplot(allData, aes(x = factor(1), y = PChoseRisk)) + geom_boxplot() + 
  theme_classic() + theme(plot.title = element_text(face="bold", size = 16)) +
  ggtitle("Prop chose risky")
print(p)

p <- ggplot(allData, aes(PChoseRisk)) + geom_histogram(binwidth=0.1) +
  theme(plot.title = element_text(face="bold", size = 16)) + ggtitle("Prop chose risky")
print(p)
```
\newpage

## Plot individual kids' data
```{r, echo=FALSE, warning=FALSE, message=FALSE}
require(reshape2)
kidAmbigStairs <- ambig[,c(ambigEnd:ambigStart)]
kidAmbigStairs <- kidAmbigStairs[with(kidAmbigStairs, order(RA0_6, RA1_5, RA2_4, RA3_3, RA4_2, RA5_1, RA6_0)),]
colnames(kidAmbigStairs) <- c("0/6", "1/6", "2/6", "3/6", "4/6", "5/6", "6/6")

kidAmbigStairs <- kidAmbigStairs == 1
row.names(kidAmbigStairs) <- 30:1
test.m <- melt(kidAmbigStairs)
p <- ggplot(test.m, aes(Var2, Var1)) + geom_tile(aes(fill = value), colour = "grey") + 
  scale_fill_manual(values = c("grey90", "black"), labels=c("Chose ambiguous", "Chose risky")) + 
  theme_classic() + 
  theme(legend.title=element_blank()) + theme(legend.text=element_text(size=12)) + 
  theme(legend.position = c(0.06,0.94)) + theme(legend.justification = c(0,1)) +
  ggtitle("All children, all trials") + theme(plot.title=element_text(face="bold", size=16)) + 
  labs(x="P(Risk)", y="Participant Number") + theme(axis.title=element_text(size=12)) + 
  theme(axis.text=element_text(size=10)) +
  scale_y_continuous(breaks=c(1,5,10,15,20,25,30))

print(p)

```
\newpage

## Plot overall logistic regression for kids
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# require(reshape2)
ambig4logit <- ambig[,ambigStart:ambigEnd]
colnames(ambig4logit) <- c("6/6", "5/6", "4/6", "3/6", "2/6", "1/6", "0/6")
ambig4logit <- melt(ambig4logit)
colnames(ambig4logit) <- c("PRisk", "ChoseRisk")

allAmbigAtt <- data.frame(colMeans(ambig[,ambigStart:ambigEnd]))
colnames(allAmbigAtt) <- "PropChoseRisk"
allAmbigAtt$PRisk <- c("6/6", "5/6", "4/6", "3/6", "2/6", "1/6", "0/6")
allAmbigAtt <- data.frame(allAmbigAtt)

p <- ggplot(allAmbigAtt, aes(x=PRisk, y=PropChoseRisk)) + geom_point() + theme_classic() +
  stat_smooth(data = ambig4logit, aes(group = 1, y = ChoseRisk), method="glm", method.args = list(family="binomial")) + 
  theme(plot.title = element_text(face="bold", size = 16)) + ggtitle("Children: Proportion chose risky by P(Risk)") + 
  theme(axis.title=element_text(size=12)) + theme(axis.text=element_text(size=10))
print(p) 

```

## Plot individual data and logit on same plot
```{r, echo = F, warning = F, message = F}
require(gtable)

test.m2 <- test.m

p1 <- ggplot(test.m2, aes(Var2, Var1)) + geom_tile(aes(fill = value), colour = "grey") + 
  scale_fill_manual(values = c("grey90", "grey70"), labels=c("Chose ambiguous", "Chose risky")) + 
  theme_classic() + 
  theme(legend.title=element_blank()) + theme(legend.text=element_text(size=16)) + 
  theme(legend.position = c(0.06,0.94)) + theme(legend.justification = c(0,1)) +
  labs(x="Risky P(Win)", y="Participant number") + theme(axis.title=element_text(size=20)) + 
  theme(axis.text=element_text(size=16)) +
  scale_y_continuous(breaks=c(1,5,10,15,20,25,30))+ theme(plot.margin = unit(c(1,2,1,2), "lines"))

p2 <- ggplot(allAmbigAtt, aes(x=PRisk, y=PropChoseRisk)) + geom_point() + 
  stat_smooth(data = ambig4logit, aes(group = 1, y = ChoseRisk), method="glm", method.args = list(family="binomial")) + 
  theme_classic() %+replace% theme(panel.background = element_rect(fill = NA)) + 
  theme(axis.title.y=element_text(angle = 270)) +
  theme(axis.title=element_text(size=20)) + theme(axis.text=element_text(size=16)) + 
  labs(y = "Proportion chose risky") 

#extract gtable
g1 <- ggplot_gtable(ggplot_build(p1))
g2 <- ggplot_gtable(ggplot_build(p2))

#overlap plots
pp <- c(subset(g1$layout, name == "panel", se = t:r))
g <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, pp$l, pp$b, pp$l)

# axis tweaks
ia <- which(g2$layout$name == "axis-l")
ga <- g2$grobs[[ia]]
ax <- ga$children[[2]]
ax$widths <- rev(ax$widths)
ax$grobs <- rev(ax$grobs)
ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths) - 1)
g <- gtable_add_grob(g, ax, pp$t, length(g$widths) - 1, pp$b)

g <- gtable_add_grob(g, g2$grob[[7]], pp$t, length(g$widths), pp$b)
# draw it
grid.draw(g)

```

